# Generated by Django 3.0.6 on 2020-06-08 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PizzaModeel',
            new_name='PizzaModel',
        ),
    ]
